steps:
  #Upload DAGs to Cloud Storage
  - name: 'google/cloud-sdk'
    id: 'Upload DAGs'
    args:
      - 'gsutil'
      - 'rsync'
      - '-r'
      - '-d'
      - 'dags/'
      - 'gs://us-central1-airflow-cf62a32c-bucket/dags/'

timeout: '1200s'

serviceAccount: 'projects/airbnb-448411/serviceAccounts/sayliyev.f@gmail.com'
logsBucket: 'gs://airbnb-chicago/temp/'
  