steps:
  # Step 1: Lint the DAGs (optional)
  - name: 'python:3.11'
    id: 'Lint DAGs'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install pylint
        pylint dags/

  # Step 2: Upload DAGs to Cloud Storage
  - name: 'google/cloud-sdk'
    id: 'Upload DAGs'
    args:
      - 'gsutil'
      - 'rsync'
      - '-r'
      - '-d'
      - 'dags/'
      - 'gs://us-central1-airflow-9dc9b24d-bucket/dags/'

  # Step 3: Run Tests (optional)
  - name: 'python:3.11'
    id: 'Run Tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install pytest
        pytest tests/

# Timeout for the build (optional)
timeout: '1200s'

# Service account for Cloud Build (optional but recommended)
options:
  logging: CLOUD_LOGGING_ONLY
  #workerPool: 'projects/airbnb-448411/locations/us-central1/workerPools/<WORKER_POOL_NAME>'
  serviceAccount: 'projects/airbnb-448411/serviceAccounts/sayliyev.f@gmail.com'
  logsBucket: 'gs://airbnb-chicago/temp/'